CREATE DATABASE IF NOT EXISTS dompetku_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dompetku_app;

CREATE TABLE wallets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type ENUM('MAIN', 'INVESTMENT') NOT NULL,
  openingSaldo DECIMAL(15,2) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type ENUM('INCOME', 'EXPENSE', 'INVESTMENT') NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE investment_assets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  walletId INT NOT NULL,
  assetType ENUM('REKSADANA', 'EMAS') NOT NULL,
  subType VARCHAR(100) NULL,
  assetName VARCHAR(255) NOT NULL,
  platform VARCHAR(100) NULL,
  quantity DECIMAL(15,4) NULL,
  avgBuyPrice DECIMAL(15,2) NULL,
  currentPrice DECIMAL(15,2) NULL,
  totalInvested DECIMAL(15,2) NOT NULL DEFAULT 0,
  totalValue DECIMAL(15,2) NOT NULL DEFAULT 0,
  isVoided BOOLEAN NOT NULL DEFAULT FALSE,
  voidedAt DATETIME NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_asset_wallet FOREIGN KEY (walletId) REFERENCES wallets(id) ON DELETE CASCADE
);

CREATE TABLE transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  walletId INT NOT NULL,
  categoryId INT NULL,
  type ENUM('INCOME', 'EXPENSE', 'TRANSFER', 'INVESTMENT_BUY') NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  note TEXT NULL,
  transactionDate DATETIME NOT NULL,
  assetId INT NULL,
  isVoided BOOLEAN NOT NULL DEFAULT FALSE,
  voidedAt DATETIME NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_tx_wallet FOREIGN KEY (walletId) REFERENCES wallets(id) ON DELETE CASCADE,
  CONSTRAINT fk_tx_category FOREIGN KEY (categoryId) REFERENCES categories(id) ON DELETE SET NULL,
  CONSTRAINT fk_tx_asset FOREIGN KEY (assetId) REFERENCES investment_assets(id) ON DELETE SET NULL
);

CREATE TABLE investment_snapshots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  assetId INT NOT NULL,
  monthKey VARCHAR(7) NOT NULL,
  value DECIMAL(15,2) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_snapshot_asset FOREIGN KEY (assetId) REFERENCES investment_assets(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_snapshot_asset_month (assetId, monthKey),
  INDEX idx_snapshot_month (monthKey)
);

INSERT INTO wallets (name, type, openingSaldo)
VALUES
('Dompet Utama', 'MAIN', 5000000),
('Dompet Investasi', 'INVESTMENT', 0);

INSERT INTO categories (name, type)
VALUES
('Gaji', 'INCOME'),
('Pemasukan Lain', 'INCOME'),
('Makan', 'EXPENSE'),
('Kebutuhan', 'EXPENSE'),
('Transfer', 'EXPENSE'),
('Mendesak', 'EXPENSE'),
('Tagihan', 'EXPENSE'),
('Investasi', 'INVESTMENT');
